### ISSUE TITLE
Missing artifact com.se2automate.voice:VoiceAutomationClient:jar:1.0.0

### ISSUE THREAD

**Issue by vidyasagarpogiri** [g-tiwari/GoogleVoiceTest#1]
I've cloned your repo and updated pom.xml but still I'm unable to resolve the issue.Please look into the attached screenshot and help me to resolve this issue. Thank you.

![07-27-2018 16_00_19-greenshot](https://user-images.githubusercontent.com/7712928/43316213-2e77a6fe-91b6-11e8-8e2d-147744727bcc.png)

**Comment by vidyasagarpogiri** [comment]
@g-tiwari , please help me in resolving this.

**Comment by g-tiwari** [comment]
Hey vidyasagarpogiri,
As of now, the maven repository is down for the VoiceAutomationClient pom.
I am working on some fixes and making package level changes.

I will get back to you once I put this repo back

Thanks

**Comment by vidyasagarpogiri** [comment]
Thanks for the update. Kindly keep me posted once it's up and running. I'm planning to give a presentation in my office.

**Comment by g-tiwari** [comment]
Hey @vidyasagarpogiri 
I have updated the VoiceAutomationClient library now the version is 1.0.1
Please pull the latest code for this GoogleVoiceTest repo and try

**Comment by vidyasagarpogiri** [comment]
@g-tiwari , thank you for the update .

**Comment by vidyasagarpogiri** [comment]
Hey @g-tiwari sorry to bother you. Still I'm facing the same issue.Please help me out , thank you.

![08-06-2018 15_43_59-greenshot](https://user-images.githubusercontent.com/7712928/43711123-5c45762a-998f-11e8-87d6-6f757fb1c012.png)

**Comment by g-tiwari** [comment]
This is now resolved, closing the issue.
