### ISSUE TITLE
Need some info about this project

### ISSUE THREAD

**Issue by truptibhatt** [g-tiwari/GoogleVoiceTest#3]
Thanks a a lot for sharing the code.
Few queries: 

-->I have downloaded this project plus VoiceAutomationServer-1.0.0.jar , starting server by
java -jar VoiceAutomationServer-1.0.1.jar

and then from Google Voice Test opening cmd and running
 mvn test -DVoiceAutomationServerEndpoint="" -DVoiceRssKey="<API_Key_FromVoiceRSS>"

Can you explain what does it mean?

--> It is throwing an error in gsri_ok0. which is this id? use-fake-ui-for-media-stream=1, it means it will allow microphone right? It is stuck in after above locator. Can you help me?
Thank you,
Trupti

**Comment by g-tiwari** [comment]
Hey Trupti,
-D variables passed from command line are used by GoogleVoiceTest code. Server end point is required for communicating voice client to voice server. 
Regarding the error, I would be able to help if you can paste the complete staketrace here

Gaurav

**Comment by g-tiwari** [comment]
Hey,

I just figured out that few locators on Google page has changed, I have updated them and pushed code.
Please take "git pull" and try again

**Comment by truptibhatt** [comment]
> Hey Trupti,
> -D variables passed from command line are used by GoogleVoiceTest code. Server end point is required for communicating voice client to voice server.
> Regarding the error, I would be able to help if you can paste the complete staketrace here
> 
> Gaurav

Thanks Gaurav,

Can you tell me how to find VoiceAutomationServerEndpoint and API_Key_FromVoiceRSS?
mvn test -DVoiceAutomationServerEndpoint="" -DVoiceRssKey="<API_Key_FromVoiceRSS>"

**Comment by g-tiwari** [comment]
> > Hey Trupti,
> > -D variables passed from command line are used by GoogleVoiceTest code. Server end point is required for communicating voice client to voice server.
> > Regarding the error, I would be able to help if you can paste the complete staketrace here
> > Gaurav
> 
> Thanks Gaurav,
> 
> Can you tell me how to find VoiceAutomationServerEndpoint and API_Key_FromVoiceRSS?
> mvn test -DVoiceAutomationServerEndpoint="" -DVoiceRssKey="<API_Key_FromVoiceRSS>"

Hey, 
You need to create an account on http://www.voicerss.org/login.aspx and get the api key from there. VoiceAutomationServerEndpoint can be found when you execute `java -jar VoiceAutomationServer-1.0.1.jar` you will see an url with port in the end. Just copy that and use here.

Please close this query once you are able to execute the test

**Comment by g-tiwari** [comment]
Closing this issue now, I hope this is now resolved
